### ISSUE TITLE
Reenable tests

### ISSUE THREAD

**Issue by ethanwhite** [weecology/PortalData#100]
I suspect that in setting up the CI to do the updating we actually stopped the tests from running.

**Comment by gmyenni** [comment]
There wasn't a `testthat.R`. Now there is, though, tests still aren't running yet. It seems like tests automatically run last, but we actually need them to run first, before sourcing the table updates.

**Comment by gmyenni** [comment]
Or would it be better to just figure out how to rewrite the tests so they don't rely on comparing '(data, newdata)'?

**Comment by gmyenni** [comment]
I don't think tests were ever running, actually. Done in #115
