### ISSUE TITLE
Standardize column names

### ISSUE THREAD

**Issue by gmyenni** [weecology/PortalData#101]
Change all column names to this standard set (@emchristensen change/add however you see fit)

year, month, day, date, period, plot, stake, newmoonnumber, treatment, speciescode, quadrat

**Comment by emchristensen** [comment]
in the Portal_plant_quadrats.csv file, should there be a column named "quadrant"?  I'm pretty sure I didn't mess with that file.  Just want to make sure nobody did that on purpose for some reason before I change it to "quadrat" @gmyenni

**Comment by gmyenni** [comment]
Woah, that's blowing my mind. Was it always like that? (It should be `quadrat`.)

**Comment by emchristensen** [comment]
No idea how long it's been like that, I'll just go ahead and change it...
