### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by ethanwhite** [weecology/PortalData#102]
We should add a license to make it clear to folks that the data is openly available.

[CC0]( is generally agreed to be the best license for data to facilitate reuse and combination with other datasets:

* https://blog.datadryad.org/2011/10/05/why-does-dryad-use-cc0/
* http://www.dancohen.org/2013/11/26/cc0-by/
* https://creativecommons.org/share-your-work/public-domain/cc0/

It doesn't require attribution, but the idea is that citation is required anyway by scientific cultural norms and ethics in the same way that citing papers (not a legal requirement) is expected. This is the license that Dryad uses and that figshare uses for datasets, so it's pretty standard.

**Comment by gmyenni** [comment]
https://github.com/weecology/PortalData/commit/6d3ae57604772f00d88b8dd86218442ed727372b
