### ISSUE TITLE
How to keep track of plant census dates

### ISSUE THREAD

**Issue by gmyenni** [weecology/PortalData#114]
As it is now, `Portal_plant_census_dates.csv` still needs to be updated manually. We don't add census days or months when we enter the data, or anywhere else in the repo. So there's no way to get them but entering them by hand. Alternatively, we could add `day` and `month` columns in `Portal_plant_quadrats.csv` since we do record that on the datasheets. We'd just have to deduce those as best we could from the old datasheets, where they may or may not have bothered to record it.

**Comment by emchristensen** [comment]
what if we add month and day columns to Portal_plant_censuses instead?  I think that's too many columns (that mostly nobody will care about) for Portal_plant_quadrats.

**Comment by gmyenni** [comment]
Yeah, that would probably be a better place to put them. But it still wouldn't build automatically. Again, because there's nowhere to get that date information. We would have to go back to entering data into `Portal_plant_censuses.csv` by hand.

**Comment by emchristensen** [comment]
we would have to build it from the raw data in the dropbox -- that's where that information is lost right, going from the cleaned dropbox data to the database?  looks like all that happens in PortalData/DataCleaningScripts/clean_plant_quadrat_data.R
we could totally add in some code to append new dates to Portal_plant_censuses.csv or Portal_plant_census_dates.csv

**Comment by gmyenni** [comment]
Oh yeah, the raw data has `year` `month` `day`.

It would be easiest to just leave those in, then. You think it would be better to have them in `Portal_plant_censuses.csv`?

Also, whichever we decide, we'll have to go back in time and assign dates as best we can to previous years. Pre-2011 we may have to do some guessing. 2011-2015 we'll have to add dates, but we'll know what they were at least. I guess adding them to `Portal_plant_censuses.csv` will make this manual part easier than adding them to `Portal_plant_quadrats.csv`.

And doing this will make `Portal_plant_census_dates.csv` obsolete. So we'll be able to delete that not very useable file once we're done.

**Comment by emchristensen** [comment]
Yeah I guess that's really the question, whether we want to keep that file or not (and probably write a summary script that will extract just the date info if you want).  I really don't know what would be better.  I actually have looked at the Portal_plant_census_dates.csv file just to get a quick look and confirm that the plant censuses were kind of done at the same time every year... but it's an awkward file, with the multiple numbers in the month and day columns.  I guess it should go :(

**Comment by gmyenni** [comment]
So maybe `Portal_plant_census_dates.csv` is useful?

It is nice to have a short table where you can look up if a census was done or not. And the only way `day` gets used is just for scheduling. Even if someone wanted to actually use `month`, they could pull it from `Portal_plant_census_dates.csv`.

Maybe we could switch the columns to `start_month` `end_month` `start_day` `end_day`. Or just `start_date` `end_date`. Then extract `day` and `month` during the data cleaning process to update the table.

**Comment by emchristensen** [comment]
If it's just being used as a way to quickly look up censuses I don't think we need to change it -- I think it makes most sense the way it is for humans looking at it, it might only be weird if you tried to code with it.  I say let's leave it as is.

**Comment by gmyenni** [comment]
Okay, let me close this issue and open a more specific one instead, then.
