### ISSUE TITLE
Rewrite rodent data entry tests to work with Travis

### ISSUE THREAD

**Issue by gmyenni** [weecology/PortalData#116]
I enabled the tests in `testthat`, but the rodent data entry tests can't pass the way they're written now. We need rodent data tests that will work remotely. Right now, they (at least some of them) rely on local files (like scannerfile?). @bleds22e, do you currently use these? I think you and @emchristensen both have references to your local files in here. Is it possible to make generic versions of those that can work with testing, but still have the functions useable with real data files for new data entry (like @emchristensen did with the rodent test file or something)?

**Comment by bleds22e** [comment]
Yes, I do currently use these. We can probably figure out something like that.

**Comment by emchristensen** [comment]
the scannerfile is the downloaded pit tags from the pit tag scanner.  it lives in the dropbox.  can we access the dropbox without using local paths?

**Comment by bleds22e** [comment]
I was wondering that myself. I don’t know how to do it, if it’s possible.
On Sep 25, 2017, at 8:40 AM, Erica Christensen <notifications@github.com<mailto:notifications@github.com>> wrote:


the scannerfile is the downloaded pit tags from the pit tag scanner. it lives in the dropbox. can we access the dropbox without using local paths?

**Comment by gmyenni** [comment]
For Dropbox files, just switch to using the Dropbox link to the file (and change dl=0 to dl=1). e.g. `read.csv(url('https://www.dropbox.com/s/kbbaohuxh4xc1cs/tags466.txt?dl=1'), header = T)`.

But first you need to think about what makes the most sense for the `test-` file. Of course the newdatxxx.csv and tagsxxx.txt files need to be used for data cleaning. But do you also want to use those new files for testing?

If you're using them for testing, so the Dropbox link doesn't need to be changed every month, you can just add new data without the period code (so the tags file is just tags.txt, the newdat file is just newdat.csv). Then once it's been cleaned it can get the period code suffix, and the net set of newdata will replace it, etc.

Or do you just want to create dummy files that don't change, just so you can test that the cleaning functions are theoretically working (e.g. in case you edit them)?

**Comment by emchristensen** [comment]
we fixed the path issues in the rodent tests.  they work when I run them on my machine but still fail in the Travis build.  something about a setwd() command but we don't know where that is.  you need to tell us why it's still failing @gmyenni

**Comment by gmyenni** [comment]
It's not able to find `moon_dates.csv`. Though it looks like a new row was added for the latest data. Or was that done manually?

**Comment by emchristensen** [comment]
which script is trying to find moon_dates.csv?  Yeah, it just got updated with the addition of July rodent data

**Comment by gmyenni** [comment]
The tests and the function to update `moon_dates.csv` automatically.

**Comment by gmyenni** [comment]
I started a new PR to start weeding out errors.

**Comment by emchristensen** [comment]
oh, do we want it to update moon_dates automatically?  There's also some code at the end of the script we use to clean new rodent data that does this -- that's what Renata just used to update it when she put did period 464

**Comment by gmyenni** [comment]
I fixed the `moon_dates.csv` problem.
Next, openxlsx needs to be loaded in Travis. Are you going to use that from now on? Can I get rid of XLConnect?

**Comment by emchristensen** [comment]
oh yeah, all those paths you just changed we had just changed this morning when we were running it locally

**Comment by emchristensen** [comment]
yes; apparently XLConnect doesn't work on mac very well

**Comment by gmyenni** [comment]
Oh, yeah. The moon numbers, trapping table, weather, etc are all already updating automatically. You shouldn't be adding those manually.

**Comment by emchristensen** [comment]
ok then!

**Comment by bleds22e** [comment]
Gotcha. I was recalling this morning that the manual addition to those tables was a temporary fix

**Comment by gmyenni** [comment]
The travis.yml (https://github.com/weecology/PortalData/blob/master/.travis.yml) is where you can find what is getting sourced on Travis. All you need to do is make sure that those scripts are doing what they need to do. And that when that stuff gets called, it will work on Travis. e.g. I changed the paths for finding `moon_dates.csv`, because Travis is either working inside `testthat` or `DataCleaningScripts`.

**Comment by emchristensen** [comment]
ohhh ok

**Comment by gmyenni** [comment]
Oh, and when you test stuff locally, basically you should do it from within whatever working directory Travis will be in. So when you run the tests, you should be in `testthat`. When you run cleaning scripts, you should be in `DataCleaningScripts`. Not just in `PortalData`.

**Comment by emchristensen** [comment]
Travis is complicating everything
