### ISSUE TITLE
Quadrat abundance issues

### ISSUE THREAD

**Issue by gmyenni** [weecology/PortalData#144]
Can someone in the lab check the datasheets for some odd abundances (below)? I'm not surprised by the grasses, but it seems odd that there would be 1394 *Eriastrum*, or 1600 *Haplopappus*. 

Also, all the `NA`s in 2014? 

`data[which(!(data$abundance %in% 0:1000)),]`

`year season plot quadrat   species abundance cover cf

4649   1983 winter   23      57 eria diff      1394    NA   

5993   1984 winter    1      17 eria diff      1116    NA   

6413   1984 winter    4      31 eria diff      1207    NA   

6419   1984 winter    4      33 eria diff      1078    NA   

7147   1984 winter   10      15 eria diff      1153    NA   

7155   1984 winter   10      17 eria diff      1341    NA   

7165   1984 winter   10      31 eria diff      1009    NA   

7180   1984 winter   10      37 eria diff      2379    NA   

7193   1984 winter   10      53 eria diff      1317    NA   

7210   1984 winter   10      57 eria diff      1436    NA   

7227   1984 winter   10      73 eria diff      1264    NA   

7236   1984 winter   10      75 eria diff      1522    NA   

7289   1984 winter   11      33 eria diff      1114    NA   

7382   1984 winter   12      33 eria diff      1472    NA   

8102   1984 winter   19      15 eria diff      1093    NA   

8111   1984 winter   19      17 eria diff      1411    NA   

8180   1984 winter   19      77 eria diff      1641    NA   

8273   1984 winter   21      11 eria diff      1334    NA   

8544   1984 winter   23      15 eria diff      1447    NA   

8589   1984 winter   23      51 eria diff      1320    NA   

24484  1989 winter    5      53 hapl grac      1070    NA  
 
24514  1989 winter    6      15 hapl grac      1600    NA  
 
24529  1989 winter    6      35 hapl grac      1636    NA  
 
24591  1989 winter    7      11 hapl grac      1064    NA  
 
24669  1989 winter    7      77 hapl grac      1695    NA  
 
24725  1989 winter    8      37 hapl grac      1103    NA  
 
24822  1989 winter    9      53 hapl grac      1052    NA  
 
24865  1989 winter   10      17 hapl grac      1436    NA 
  
24871  1989 winter   10      31 hapl grac      1104    NA 
  
24880  1989 winter   10      33 hapl grac      1292    NA 
  
25076  1989 winter   12      37 hapl grac      1580    NA 
  
25473  1989 winter   17      33 hapl grac      1021    NA 
  
25604  1989 winter   19      17 hapl grac      1372    NA 
  
25653  1989 winter   19      57 hapl grac      1284    NA 
  
25769  1989 winter   21      15 hapl grac      1008    NA 
  
25804  1989 winter   21      51 hapl grac      1484    NA 
  
25858  1989 winter   22      11 hapl grac      1071    NA 
  
26012  1989 winter   23      53 hapl grac      1604    NA 
  
26310  1989 summer    2      11 bout aris      1164    NA
   
26593  1989 summer    3      57 bout aris      1003    NA
   
26613  1989 summer    3      71 port parv      1131    NA
   
27453  1989 summer    9      11 bout aris      1142    NA 
  
27737  1989 summer   10      55 port parv      1098    NA
   
27992  1989 summer   12      17 bout aris      1182    NA
   
28008  1989 summer   12      33 bout aris      1204    NA
   
28016  1989 summer   12      35 bout aris      1298    NA
   
28056  1989 summer   12      55 bout aris      1341    NA
   
30954  1990 summer    2      11 bout aris      1281    NA 
  
30960  1990 summer    2      13 bout aris      1345    NA 
  
30971  1990 summer    2      15 bout aris      1125    NA 
  
30997  1990 summer    2      33 bout aris      1121    NA 
  
31008  1990 summer    2      35 bout aris      1346    NA 
  
31016  1990 summer    2      37 bout aris      1303    NA 
  
31261  1990 summer    4      13 bout aris      1275    NA 
  
31271  1990 summer    4      15 bout aris      1309    NA 
  
31332  1990 summer    4      53 bout aris      1140    NA 
  
31343  1990 summer    4      55 bout aris      1249    NA 
  
31351  1990 summer    4      57 bout aris      1007    NA 
  
31633  1990 summer    6      57 bout aris      1409    NA 
  
32260  1990 summer   11      31 bout aris      1022    NA
   
32631  1990 summer   14      11 bout aris      1308    NA
   
33585  1990 summer   22      33 bout aris      1123    NA
   
42032  1993 winter    1      37 hapl grac      1520    NA 
  
42050  1993 winter    1      53 hapl grac      1423    NA 
  
42080  1993 winter    1      71 hapl grac      1219    NA 
  
42098  1993 winter    1      75 hapl grac      1710    NA 
  
42544  1993 winter    5      11 hapl grac      1240    NA 
  
96869  2014 winter   19      73 astr nutt        NA    NA   

97094  2014 winter   23      35 flou cern        NA    NA   

97435  2014 summer    3      51 pani hirt        NA    NA  
 
97977  2014 summer    8      35 acac cons        NA    NA
   
98342  2014 summer   12      13 moll cerv        NA    NA
   
98442  2014 summer   13      13 kall hirs        NA    NA   

98697  2014 summer   16      13 acac cons        NA    NA
   
100325 2015 winter   13      17 acac cons        NA    NA  
 
100619 2015 winter   18      51 chae stev        NA    NA   

102177 2015 summer   16      57 bout aris      1112    70 `

**Comment by skmorgane** [comment]
I checked the data sheets for the ones through 1984. All those wierd eria diff numbers are correct. That's exactly what it says on the data sheets. I haven't checked anything post 1984.

**Comment by emchristensen** [comment]
Yep, the rest of them check out too.  The NAs are where we wrote down the species but failed to write a number (I don't think it's too surprising there were so many in summer 2014, the 3 of us were so heat-addled out there)

**Comment by gmyenni** [comment]
Wow, those numbers are crazy! 

So I guess we'll just have to leave `NA`s as acceptable in the abundance column then? I don't suppose there's really any other good way to handle them.

**Comment by emchristensen** [comment]
I guess the alternative would be to assume '1' and flag them?  Most of them are probably meant to be 1 anyway. But then we'd have to make a whole other column for the flag...

**Comment by gmyenni** [comment]
Yeah, I guess just leave them. Oh well.
