### ISSUE TITLE
Add checks for body size measurements by species

### ISSUE THREAD

**Issue by gmyenni** [weecology/PortalData#150]
Add note1 = 12 for suspect mass/hindfootlength

**Comment by gmyenni** [comment]
We just realized this note exists but is underutilized.

**Comment by diazrenata** [comment]
Do you mean add expected min/max values for each species, and if a record falls outside those it gets note1 = 12? (Or to find note1 = 12 in the old datasheets - it's not on the most recent form, but I could go back and find it in older stuff).

Is there a record we usually use for usual body size measurements for different species?

**Comment by gmyenni** [comment]
Yeah, the first one. Add checks for expected min/max values for each species in the cleaning process, and add note1 = 12 to weird cases.
The Portal vets just kind of 'know' what those values are. But you could formalize it by using the data, excluding the note1 = 12's.

I'm going to add tests for this as well, so I'll take care of the second part (going through the existing data).
