### ISSUE TITLE
Add continuously updated NDVI

### ISSUE THREAD

**Issue by gmyenni** [weecology/PortalData#164]

**Comment by emchristensen** [comment]
We also need better documentation on how we computed this to begin with

**Comment by skmorgane** [comment]
We might be able to make a Landsat timeseries for Portal using this product: https://ndvi.ntsg.umt.edu/

Paper on the product https://dx.doi.org/10.3390/rs9080863

**Comment by emchristensen** [comment]
Apparently USGS completely reorganized all their landsat data in 2016. It looks like it might make data acquisition much easier. But it also means I have to redo everything we did before to get the Landsat data and write new scripts.  This will take some time.

**Comment by gmyenni** [comment]
@henrykironde , do you have ideas about how to automate pulling this data?

**Comment by henrykironde** [comment]
Will check
