### ISSUE TITLE
plant treatment table

### ISSUE THREAD

**Issue by emchristensen** [weecology/PortalData#173]
Right now we don't have a table for indicating plant treatments (e.g. annual removal plots) unless you try to decipher Portal_plot_treatments.csv in SiteandMethods.  Seems like we need something analogous to what Portal_plots.csv does for rodent treatments, in order to write functions to summarize plant quadrat data in an acceptable way.  Also ants, if we're still planning on having that data available in the future.

**Comment by gmyenni** [comment]
I would add columns for plant treatment (will it work to have plant treatment and seed treatment in the same column?) and ant treatment. Make them NA once the plant and ant treatments stop.

**Comment by emchristensen** [comment]
I like this idea.  Plant removal and seed addition could feasibly go in the same column since they didn't overlap in time, but I thought those treatments were for two different experiments? i guess both serve to either increase or decrease the food base of the rodents and ants.  but if you're just doing plant stuff you would care about the removals but not the seed addition. plus it seems like a lot to put in one column: there are three levels of seed addition (small seeds, large seeds, mixed-size) and four levels of annual removals (summer annuals, winter annuals, biseasonal annuals, all)

**Comment by skmorgane** [comment]
My understanding is that the plant and seed manipulations were trying to address the same question: what happens when you alter the rodent's resource base, either by removing seed-producing plants or adding extra seeds. This is why you don't have a seed addition-plant removal combo. So I think a single column for the plant manipulations reflects the experimental design.

**Comment by emchristensen** [comment]
Ok, I'll call that column Resource_manipulation or something, which will be a factor with 7 possible levels.  I'll be sure to add that to the Readme

**Comment by emchristensen** [comment]
Does the seed addition treatment have a similar burn-in period as the rodent treatments? (e.g. 3 periods of no manipulation)?

**Comment by skmorgane** [comment]
I dont know. Looks like probably everything had at least a 1 month burn in period. They talk about base line data collected in July. Then any poisoning started in August. All plots had large holes for rodents for July August and September and holes were reduced in size in October. All he says is that "the remaining 10 plots were initially assigned at random to...seed addition treatments." Sounds like they started pretty early. There was a paper looking at the seed addition experiment(Brown and Munger 1985). It may have more details on timings. In 1986 (no month given),  seed addition plots were reassigned to the Roundup applications.

**Comment by skmorgane** [comment]
All the info from above came from Jim's 1998 book chapter in Experimental Ecology.

**Comment by emchristensen** [comment]
@skmorgane do you have a copy of this book in your office?  I don't see it in the weecology library. I've been finding discrepancies in the literature about which plots are supposed to be ant removal plots.  I suspect there's a typo in Brown and Munger 1985.

**Comment by skmorgane** [comment]
Yes, I keep it in my office because I use it all the time! Funnily, there are definitely errors in the table in that chapter as well. I think 23 or 24 is wrong, can't remember which right now. You can swing by today and borrow the book.

**Comment by skmorgane** [comment]
Does PR #177 close this issue?

**Comment by emchristensen** [comment]
Mostly. I feel confident we know the exact dates of the rodent treatments, seed addition, and annual removal treatments (still not clear if annuals were removed from the plant quadrats or not). The ants... I feel confident what the treatments were 1977-1985 because they're written on the data sheets (note that these are not exactly what is written in Jim's book chapter). And again I found treatments written on sheets in 1998-2002.  I'm not confident about what was going on 1985-1998, but I haven't dug through the portal archive drawer yet (it's also possible I can learn something from the data itself).

**Comment by emchristensen** [comment]
Ok I'm gonna call it, at this point I think I've gotten all the information possible about the treatments. There's one more pull request in #180 with some adjustments to the spectab treatments, and then I think this issue is resolved to the best of our ability.
