### ISSUE TITLE
Portal_plant_census_dates: date columns

### ISSUE THREAD

**Issue by emchristensen** [weecology/PortalData#174]
In this table we keep track of the start and end date of each plant census.  Month and day are stuck together in a column
> head(date_table)
  year season censusdone start   end
1 1981 summer        yes 10-29 10-31
2 1982 winter        yes  5-19  5-20
3 1982 summer        yes   9-8  9-11
4 1983 winter        yes  4-17  4-23
5 1983 summer        yes  8-28  8-30
6 1984 winter        yes   3-6  3-14

It would be easier to use these dates if we split month and day into different columns: start_month, start_day, end_month, end_day

Any objections?

**Comment by gmyenni** [comment]
Sounds fine to me.

**Comment by emchristensen** [comment]
pull request.  tragically the file Methods.md got mixed up in all this and I can't make it go away

**Comment by gmyenni** [comment]
merged
