### ISSUE TITLE
Versioning Numbering

### ISSUE THREAD

**Issue by gmyenni** [weecology/PortalData#178]
Establish versioning scheme for new releases.

**Comment by skmorgane** [comment]
I'm making a different versioning issue, so I edited the name of this one to make it clearer how they're different

**Comment by ethanwhite** [comment]
We've decided to follow the standards we helped develop here:
https://frictionlessdata.io/specs/patterns/

Major version: changes in data structure
Minor version: new data
Patch version: changes to existing data
