### ISSUE TITLE
Portal_plant_censuses.csv does not contain Summer 2017 census

### ISSUE THREAD

**Issue by emchristensen** [weecology/PortalData#179]
does this file update automatically?  Summer 2017 has been added to Portal_plant_quadrats.csv but it is not in Portal_plant_censuses.csv

**Comment by gmyenni** [comment]
It should, with `update_portal_plant_censuses.R`. Looks like it's not working.
Also, I bet updating `Portal_plant_census_dates.csv` can be automated now, with the new better columns.
