### ISSUE TITLE
Landsat8 NDVI issue

### ISSUE THREAD

**Issue by skmorgane** [weecology/PortalData#195]
On pr #194 Erica mentioned that Landsat 8 seems different. I found this paper that says it has an equation for matching Landsat 8 to Landsat 7 NDVI. We may want to also check to make sure the others don’t need something similar. I seem to remember that one of the satellites was ‘off’.

https://www.sciencedirect.com/science/article/pii/S0034425715302455

**Comment by gmyenni** [comment]
This seems like more of an NDVIning issue, so I'm going to move it over there.
