### ISSUE TITLE
Add tests of the plant data cleaning process

### ISSUE THREAD

**Issue by gmyenni** [weecology/PortalData#211]
Similar to how [rodent_test_data](https://github.com/weecology/PortalData/blob/master/DataCleaningScripts/rodent_test_data.xlsx) and [test_tags](https://github.com/weecology/PortalData/blob/master/DataCleaningScripts/test_tags.txt) are used to test that the rodent cleaning functions are working correctly in [test-rodent-functions](https://github.com/weecology/PortalData/blob/master/testthat/test-rodent_functions.R).

We need a quadrat_test_data.xlsx and a test-clean_plant_quadrat_data.R.

**Comment by emchristensen** [comment]
can close this when #230 is merged
