### ISSUE TITLE
Track down remaining RAs

### ISSUE THREAD

**Issue by gmyenni** [weecology/PortalData#218]
S. K. Morgan Ernest,
Glenda M. Yenni,
Ginger Allington,
Ellen K. Bledsoe,
Erica M. Christensen,
Charles Curtin
Renata Diaz,
Keith Geluso,
Jacob R. Goheen,
Edward Heske
Douglas Kelt
Joan M. Meiners,
Jim Munger
Qinfeng Guo
Richard Inouye
Mark Putze
Dov Sax
Michelle R. Schutzenhofer,
Marian Skupski
Sarah R. Supp,
Shawn Taylor,
Katherine M. Thibault,
Ethan White,
Diane Davidson,
James H. Brown,
Thomas J. Valone 

I (Morgan) think this list currently includes everyone back through 1990 and a few individuals from before that

**Comment by skmorgane** [comment]
We should probably get started on this. It makes sense to a) ask them if they want to be listed as a co-author on this and b) provide a link to the doc so they can glance at it and also provide any comments if they have knowledge we're missing.

**Comment by gmyenni** [comment]
RAs have been emailed
