### ISSUE TITLE
Writers finish their topics

### ISSUE THREAD

**Issue by gmyenni** [weecology/PortalData#220]
Put the final touches on your assigned topic throughout the paper, ensure that formatting matches other topics in the same section:

- [ ] @diazrenata - rodents

- [ ] @bleds22e - plants

- [ ] @beecycles - ants

- [x] @sdtaylor - ndvi

- [x] @emchristensen - treatments

**Comment by gmyenni** [comment]
We'll soon be sending a link to everyone on the author line. So make sure your topic is ready for that!

**Comment by sdtaylor** [comment]
can you check mine? I don't have access to edit it.
