### ISSUE TITLE
All writers have a read-through

### ISSUE THREAD

**Issue by gmyenni** [weecology/PortalData#221]
- [x] @diazrenata

- [x] @bleds22e

- [x] @beecycles

- [x] @sdtaylor

- [x] @emchristensen

- [x] @skmorgane 

- [x] @ethanwhite 

- [x] @gmyenni

**Comment by sdtaylor** [comment]
:+1:

**Comment by beecycles** [comment]
I don't seem to be able to check the box off next to my name, but I'm done with edits.

**Comment by emchristensen** [comment]
(I checked off for Joan and Shawn since I seem to have power they do not...)

**Comment by sarahsupp** [comment]
This is really cool everyone! I finally had a window for a full read through. Thanks for including me! 😺
