### ISSUE TITLE
Automate reducing trap effort when note1=14

### ISSUE THREAD

**Issue by gmyenni** [weecology/PortalData#238]
Note 14 means 'plot incompletely trapped.' Add code to search for this automatically and reduce effort per plot (by the number of note 14s entered).

**Comment by gmyenni** [comment]
TBH, I can't really figure out how to automate this. @bleds22e and @diazrenata I think we had a conversation about this?
But, when I went to do it, I got hung up on the fact that empty rows will be cleaned out before the data get added, so this will have to be added, if we want it, at the data cleaning step.

**Comment by diazrenata** [comment]
Also, in digging on this I found that the `qflag` column in the trapping table looks like it hasn't been updating correctly since January 2018? It looks to me like the update_trapping_table.R script should set it to 0 and then to 1 when the script finishes as long as the dates for the periods being added are prior to Sys.date. But they're 0 for all the recent data? Not sure if this is a new issue, or related to something already known, or expected behavior.

**Comment by gmyenni** [comment]
This issue is about what to do when less than 49 traps get set on a plot (accidentally), and if it's possible to automate adding a number other than 49 in the effort column, just based on new data. We had a conversation about this where we thought maybe we could add a row and note 14 for every trap not set. But those empty rows will get cleaned out before the data get added, so they won't be there for the trapping table to see. Unless you or @bleds22e can remember how we were going to make that work?

The simplest thing is to just make a note in the field, including the exact number of traps missed, and then change effort in the trapping table manually. But, that never actually happens (period 371 is the only time), so we were brainstorming a way to automate it. The only partial automation I can see is if there is note 14 in the data, the cleaning script just throws a reminder to change effort in the trapping table.

`qcflag` is used to indicate data that are still potentially undergoing quality control (that we could still discover an error in species, etc. during the cleaning of new data), that we recommend not be used yet (unless you absolutely need the current data). We recommend not using the latest year of data. So it looks like the flagging is working correctly.

**Comment by diazrenata** [comment]
I understand now, thanks! Apologies if I was unhelpful.

I honestly don’t remember the initial idea, and I don’t really see a way to
automate other than the flagging you describe!
