### ISSUE TITLE
Data Workflow Cover Letter

### ISSUE THREAD

**Issue by ethanwhite** [weecology/PortalData#240]
Since we're going after a "name brand" journal we'll need a cover letter that makes a compelling argument for why the paper is important.

**Comment by ethanwhite** [comment]
@KristinaRiemer, could you attached a copy of our recent eLife cover letter here as an example?

**Comment by KristinaRiemer** [comment]
[cover_letter.pdf](https://github.com/weecology/PortalData/files/2045661/cover_letter.pdf)

**Comment by skmorgane** [comment]
Cover letter for the paper is now in the google drive folder
