### ISSUE TITLE
downloading the weather data can time out

### ISSUE THREAD

**Issue by ha0ye** [weecology/PortalData#248]
In `new_weather_data.R`, the `new_met_data()` script tries to download the data from a webserver, which can be slow to respond. Here's the table](http://166.153.133.121/?command=TableDisplay&table=MET&records=1000) that it tries to load first.

The package we're using to scrape the data into a data.frame doesn't have a timeout option, but it uses the `httr` package, which does. We can add a line in that function to set the maximum time to wait before error-ing:
`httr::set_config(httr::timeout(seconds = 60))`

And perhaps wrap the download calls in a `tryCatch` to give a more informative error message.

This doesn't actually fix the problem of the website not responding, but at least will make the Travis logs more transparent.

**Comment by ethanwhite** [comment]
Fixed in 240038e614ce3bdfa53afa3d94e3d98a9eead7e9.
