### ISSUE TITLE
Fix hard coded paths in some cleaning scripts

### ISSUE THREAD

**Issue by ethanwhite** [weecology/PortalData#273]
See https://github.com/weecology/PortalData/search?q=Dropbox&unscoped_q=Dropbox

**Comment by gmyenni** [comment]
@diazrenata, something to do next time you add rodent data?

**Comment by diazrenata** [comment]
Happy to, but I don't know what to change it to? As far as I know these are to access Dropbox, which isn't public and would live somewhere different on different machines? 

The simplest fix I see is to have the user specify the Dropbox path once per cleaning script. Is that good enough?

**Comment by gmyenni** [comment]
I *think* this just means using `"~/Dropbox/Portal/PORTAL_primary_data/...`. Like in [old_weather_overlap.R](https://github.com/weecology/PortalData/blob/master/DataCleaningScripts/old_weather_overlap.R).
 
That should work fine as long as everyone's Dropbox is in the root of their user folder (which it looks like yours is).

(@ethanwhite correct me if you were meaning something else.)

**Comment by gmyenni** [comment]
Oh, actually, even better, we could switch to using the here package: https://github.com/jennybc/here_here

That should 'just work' for everyone, regardless of where their Dropbox folder is.

**Comment by diazrenata** [comment]
It looks like here finds the base of the project working directory - are you also envisioning a way to get it to find Dropbox outside the project file structure?

**Comment by ethanwhite** [comment]
This works for me. Thanks!
