### ISSUE TITLE
Require version tags to be used in all commits?

### ISSUE THREAD

**Issue by gmyenni** [weecology/PortalData#293]
Now that tags for version naming are actually working, should we require them to be used? (Return an error on pull requests with no tag?)

**Comment by diazrenata** [comment]
I have no objection, and from my perspective it seems like that might make for a generally more robust pipeline? I'm not 100% on the details but I think right now we need R to figure out what kind of changes are in a PR, which I could see behaving strangely. Also, it would encourage me/us/anyone new to make just one kind of change per PR.

**Comment by bleds22e** [comment]
Yep, I’m ok with that
