### ISSUE TITLE
Check tags in commit messages

### ISSUE THREAD

**Issue by ha0ye** [weecology/PortalData#298]
I think [git hooks](https://githooks.com/) can be used to add instructions to the default commit message, and also to check that a tag is included in a commit message. Might not be a big deal for folks who are already regularly updating PortalData, but a useful feature to include in livedat?

**Comment by ethanwhite** [comment]
:+1: we do something like this in the `retriever` https://github.com/weecology/retriever/blob/master/hooks/pre-commit (though it's a lot more complicated).

**Comment by gmyenni** [comment]
We really need to do this.
