### ISSUE TITLE
Add code check for double-recaps in the same period

### ISSUE THREAD

**Issue by bleds22e** [weecology/PortalData#316]
We've run into the problem a couple times now where the code says we have a new tag that needs a star but that new tag is on a removal. Sometimes this is because that rodent was caught on the first night, tagged, and then caught on the second night in a removal plot.

It would be nice to have a line of code that tells us that information.

**Comment by diazrenata** [comment]
Do we want a data flag note1 = 19 for this? 

And if so do we want to add it retroactively to past censuses? I'm fiddling around right now and there are ~800 instances of the same tag occurring twice in a single period (not counting NA/0/-1 or negative period codes).

**Comment by bleds22e** [comment]
Hm. I don't think we really need to add a note1 code for it. I think the bigger issue at hand is having the QAQC code flag it if it comes up to remind us that it is a possibility if we're confused about why it doesn't have a code.


Ellen K. Bledsoe

Ph.D. Candidate, Interdisciplinary Ecology

School of Natural Resources and Environment

Dept. of Wildlife Ecology and Conservation

University of Florida

ellen.bledsoe@ufl.edu
she/her/hers

________________________________

**Comment by diazrenata** [comment]
🙌 that's significantly easier. #318 implements the change to the QA process.
