### ISSUE TITLE
Choose offifical site lat/long

### ISSUE THREAD

**Issue by skmorgane** [weecology/PortalData#364]
Just realized that we don't seem to have a lat/long for the site in the Data Paper. We should figure out what the center of the site is and use that as the generic site designation (and add to the BioRxiv paper on the next update.

**Comment by skmorgane** [comment]
Ok, apparently we have one in the Methods.md in the repo, so maybe it's in the Data Paper and I'm missing it? So I'm changing this issue to just checking on whether there is a lat/lon for the site in the Data Paper and (if not) making sure it gets added when we next update that.

**Comment by gmyenni** [comment]
Added to doc, update needs to be submitted.
