### ISSUE TITLE
getSpatialData errors

### ISSUE THREAD

**Issue by gmyenni** [weecology/PortalData#385]
I get random errors in the Travis build from the update ndvi step ([update_ndvi.R](https://github.com/weecology/PortalData/blob/master/DataCleaningScripts/update_ndvi.R)).
ie There are new data and it retrieves them fine, but then a getSpatialData function errors in processing, or in totally unrelated login issues. This can mask more relevant errors that happen later in the pipeline.

eg: https://travis-ci.org/github/weecology/PortalData/builds/752435779
There are several open issues: https://github.com/16EAGLE/getSpatialData/issues/76, https://github.com/16EAGLE/getSpatialData/issues/79

**Comment by henrykironde** [comment]
I have tried a few scripts from getSpatialData, but the error had not been the same. Can you provide some code you use to test portalduta locally

**Comment by gmyenni** [comment]
Yeah, you can source [update_ndvi.R](https://github.com/weecology/PortalData/blob/master/DataCleaningScripts/update_ndvi.R) then run lines 145 - 155. That will sometimes work fine, and sometimes give me a dimensionality error.

**Comment by gmyenni** [comment]
So @henrykironde is the error in https://travis-ci.org/github/weecology/PortalData/builds/754572011 the same as what's happening in 16EAGLE/getSpatialData#76, 16EAGLE/getSpatialData#76 then?

**Comment by henrykironde** [comment]
They are different all the time. Let me try to get the errors and report back. For now I think I should first change the logic in lines 145 - 155.

**Comment by henrykironde** [comment]
@gmyenni, let me know when you have some free time to help me clear up some issues in the code. I am getting some new errors.

**Comment by gmyenni** [comment]
Sure, this afternoon?

**Comment by gmyenni** [comment]
This seems to be working. Hopefully I'm not jinxing by closing. 🤞
