### ISSUE TITLE
CRAN issue

### ISSUE THREAD

**Issue by gmyenni** [weecology/PortalData#407]
R CMD check --as-cran leaves behind directories PortalData and old-data
in the user's home directory because \donttest sections are run by
example().  Leaving behind 183MB.

This is a serious violation of the CRAN policy.

Please correct before 2021-05-27 to retain your package on CRAN.

**Comment by ethanwhite** [comment]
Should this be in https://github.com/weecology/portalr? Also, can I get an :roll_eyes: for "serious violation of CRAN policy"?

**Comment by gmyenni** [comment]
Haha! How did I manage that?
