### ISSUE TITLE
dtplyr necessary?

### ISSUE THREAD

**Issue by skmorgane** [weecology/PortalData#44]
Is dtplyr necessary for this code to run? Just curious. In putting together a portal forecasting script to auomatically generate graphs, I'm running into the fact that everyone has different libraries they like to use/install which makes getting things up an running a nightmare. This one just bonked for me. It would be nice to get everything in the predictions pipeline on a similar set of libraries.

**Comment by gmyenni** [comment]
Nope, it's not necessary. I removed it in the new pull request.
