### ISSUE TITLE
Missing UTMs

### ISSUE THREAD

**Issue by dmcglinn** [weecology/PortalData#52]
The file `./PortalData/SiteandMethods/Portal_UTMCoords.csv` is missing UTM coordinates for two quadrats that are present in the plant survey: 
```
plot quadrat
1     77
24    17
```
Thanks for making this such a great resource!

**Comment by skmorgane** [comment]
Interesting. Plot 24 I can explain. That quadrat was destroyed in during the fence replacements in 2003 or 2004 (can't remember exactly when). So it did not exist when we took the GPS measurements. 

I have no idea what happened to plot 1 quadrat 77. It is still alive and kicking. I think @gmyenni was there when the measurements were taken, she may have insights. My guess is human error.

For both, you can guestimate it's position from the layout grid. @gmyenni: Might be useful to do that and put those locations into the file with flags or notes to indicate that they are estimates.

**Comment by gmyenni** [comment]
I wasn't there when they took those coordinates, so I don't know the story there. It probably just got missed because the rebar wasn't obvious. But we can GPS 1-77, and all the changes to Plot 24 as well, when we're there in March.

**Comment by gmyenni** [comment]
Missing UTMs are now added!
