### ISSUE TITLE
moon_dates file not automatically updating

### ISSUE THREAD

**Issue by patdumandan** [weecology/PortalData#525]

**Comment by patdumandan** [comment]
update scripts working correctly as of 31-May-2024. no code updating needed.

**Comment by patdumandan** [comment]
updating moon_dates table is erroring out: https://github.com/weecology/PortalData/actions/runs/9605034902/job/26497146067

**Comment by patdumandan** [comment]
- [ ] add test for the moon_dates table to make sure that every period in the rodents_table is matched/assigned to a newmoon number (PR #533)

**Comment by gmyenni** [comment]
Also, period 506 was never added to moondates table. Added in #534 
Added test should catch future missed census dates.
