### ISSUE TITLE
Why is the plant data split at 2015?

### ISSUE THREAD

**Issue by ethanwhite** [weecology/PortalData#54]
It looks like the plant data is split into two pieces at 2015. There are two files: `Portal_plant_2015_present.csv` and `Portal_plant_1981_2015.csv`. Is there a reason for this?

(someone is working on adding this repo to the Data Retriever so I'm just trying to understand what's happening to help them understand)

**Comment by gmyenni** [comment]
We started recording % cover by species in 2015. So <Portal_plant_2015_present.csv> has an addtional column (% cover).

**Comment by ethanwhite** [comment]
Thanks. Is there any reason not to have one file with null values in the % cover column up until that point?

**Comment by gmyenni** [comment]
That's a good question. Would that be better?

**Comment by ethanwhite** [comment]
I think so. Other wise the only way to use the entire time-series now is to import and combine two files with different columns. This isn't too bad, but it seems like an unnecessary hurdle and I don't see any downside to having a single combined file.

**Comment by gmyenni** [comment]
Alrighty I'll just combine them then.

**Comment by kvnamipara** [comment]
@gmyenni @ethanwhite 
plant datafile for data after 2015 also contain an empty column 'cf' , What is that for?

I am working on merging the two files. Do we need cf column in file?

**Comment by gmyenni** [comment]
Yes, we also need the cf column. It's used for species identification issues.

**Comment by kvnamipara** [comment]
@gmyenni 
Do you want to add cf column in newly merged csv file of plant dataset?

**Comment by gmyenni** [comment]
Combined and now called `Portal_plant_quadrats.csv`
