### ISSUE TITLE
Status of summer 2016 plant data?

### ISSUE THREAD

**Issue by ethanwhite** [weecology/PortalData#55]
It looks like maybe the Summer 2016 plant data isn't up yet. Is data entry still happening on it?

**Comment by gmyenni** [comment]
I see Summer 2016 data in `Portal_plant_2015_present.csv` and in `Portal_plant_transects_2015_present.csv`.

**Comment by ethanwhite** [comment]
Yeah, it's totally there, sorry. Looks like I was looking at the most recent release instead of the current state.
