### ISSUE TITLE
Include relative humidity data from 2002 station?

### ISSUE THREAD

**Issue by gmyenni** [weecology/PortalData#60]
Is there a reason we weren't including relative humidity in the weather table for the 2002 station ( @skmorgane ) ? Comparing it to the new station, it's gone slightly out of calibration by now, but the numbers are still reasonable. We have columns for relative humidity and battery voltage anyway now. I was thinking I could go back through the old MET files and extract this data to add to the new file. . .

**Comment by skmorgane** [comment]
No one has ever checked if it was ok data. Do any of the other regional weather stations report rel humidity? If so, we could compare with them to see if ours looks reasonable. I no problems with adding it if we have confidence in it.

**Comment by skmorgane** [comment]
Is this issue still active? If so, what state is it in? Does someone need to figure out if the rel humidity data seems reasonable? Or do we think it is and the data needs to be added to the repo?

**Comment by gmyenni** [comment]
Still active, but in the queue behind filling in weather data gaps. What needs to be done here:

- round up all the met.dat files we can find
- import and clean humidity numbers
- compare data to itself (reasonable daily and seasonality, compare to temps and precips)
- compare to regional weather (soon to exist)
- append to data (fill in already existing column)
