### ISSUE TITLE
conflicting multiple entries in Portal_plant_quadrats.csv

### ISSUE THREAD

**Issue by wpetry** [weecology/PortalData#69]
Six entries in ```Portal_plant_quadrats.csv``` are duplicated.  One appears to be a double entry error (bout aris in P20Q77 during the summer census of 2011).  The other conflicts are more opaque: Four have unequal abundances between the entries, and one has two entries under “unkn forb” which may or may not refer to the same taxon.

The script below finds and filters the  the multiple entries where ```occurrences``` is the number of times that a given year/season/plot/quadrant/species/cf combination appears in the dataset.

```
library(tidyverse)
plants <- tbl_df(read.csv("./Plants/Portal_plant_quadrats.csv", stringsAsFactors = F)) %>%
  group_by(year, season, plot, quadrant, species, cf) %>%
  mutate(occurrences = n())

# get csv row numbers of multiples
which(plants$occurrences>1)

# filter and print multiples
plants %>%
  filter(occurrences>1) %>%
  arrange(desc(occurrences)) %>%
  print(.)
```

:clap: for open data

**Comment by emchristensen** [comment]
I corrected these based on the original data sheets and field notes -- thanks for catching it!

**Comment by gmyenni** [comment]
Thanks @wpetry for the help, and for using the data! Notes on the changes here: #72

**Comment by wpetry** [comment]
Looks good, thanks!
