### ISSUE TITLE
CI needs

### ISSUE THREAD

**Issue by gmyenni** [weecology/PortalData#98]
Weather data - daily

- `new_weather_data.R`: `append_weather()`

Rodent data tables - after new data added to `Portal_rodent.csv`
    **in this order**

1.  `update_portal_rodent_trapping.R`: `writetrappingtable()`

1.  `update_portal_plots.R`: `writeportalplots()`

1.  `new_moon_numbers.R`: `writenewmoons()`

**Comment by ethanwhite** [comment]
Thanks @gmyenni.

Will it hurt anything to run the non-weather code if the data hasn't changed?

Would it cause any issues if the weather code ended up being run twice in one day?

**Comment by gmyenni** [comment]
Nope, that all should be fine. The only weak spot is that `writetrappingtable()` needs to run before `writenewmoons()`.

**Comment by ethanwhite** [comment]
This is all implemented now.
